---
language: "python"
python:
  - "2.7"
  - "3.6"

# Install python packages for ansible and linters.
install:
  - "pip install -r requirements.txt"

# Execute linting tests before running the main playbook.
# If any of these tasks fail, the entire build fails immediately.
before_script:
  - "find . -name '*.yml' | xargs yamllint -s"
  - "echo 'brkrst3310' >> ~/vault_pass_file.txt"

# Run the role playbook with mock inputs to validate the role functionality.
script:
  - "ansible-playbook tests/test_playbook.yml"
...
