---
# Install python packages for ansible and linters.
install:
  - "sudo pip install -r requirements.txt"

# Execute linting tests before running the main playbook.
# If any of these tasks fail, the entire build fails immediately.
before_script:
  - "./tests/lint.sh"

# Run the role playbook with mock inputs to validate the role functionality.
script:
  - "ansible-playbook tests/test_playbook.yml"
...
