---
all:
  vars:
    ci_test: false
    remove_files: true
    archive_format: "zip"
    scp:
      user: "nick"
      host: "192.0.2.1"
  children:
    devices:
      children:
        ios_router:
          hosts:
            csr1:
            csr2:
        iosxr_router:
          hosts:
            xrv1:
        asa_firewall:
          hosts:
            asav1:
        nxos_leaf:
          hosts:
            n3k1:
...
