---
all:
  vars:
    remove_files: true
    archive_format: "zip"
    scp:
      user: "nick"
      host: "192.0.2.1"
  children:
    devices:
      children:
        ios_router:
          hosts:
            csr1:
            csr2:
        ios_switch:  # Example group; add hosts if relevant
          vars:
            device_type: ios
        iosxr_router:
          hosts:
            xrv1:
        asa_firewall:
          hosts:
            asav1:
        asa_vpnhead:  # Example group; add hosts if relevant
...
