---
# Log in and run the commands specified in the group_vars/ files.
- name: "IOSXR >> Gather Cisco IOS-XR information"
  iosxr_command:
    provider: "{{ login_creds }}"
    commands: "{{ item.command }}"
  register: CLI_OUTPUT
  with_items: "{{ command_list }}"
  loop_control:
    label: "{{ item.command }}"
...
